### ISSUE TITLE
Strange cuts in the wavfiles and annotations

### ISSUE THREAD

**Issue by bhigy** [bootphon/zerospeech2017#1]
Hi all,

I noticed some strange cuts in the speech in on of the wavefiles (train/english/s5583.wav), for example around 8.0s and 40.5s. Is that normal?

Also, my understanding was we would get annotations for the training set. Did I misunderstand?

Thanks,
Bertrand

**Comment by jubenjum** [comment]
Hi Bertrand,

For the fist question, in the pre-processing we have to cut and/or merge the speech fragments in order to have a specific time length for a speaker, the fragmentation was done with a computed alignments that could be not perfect, that gives in certain files the problem you describe.

The idea is to test non-supervised algorithms, then we're not giving all annotations, for the track1 we give the annotations at phoneme level to evaluate your system, although the track 2 is completely non-supervised.

Juan,
The ZeroSpech Callenge Team

**Comment by bhigy** [comment]
And where should I look for these annotations?

**Comment by jukaradayi** [comment]
Hi Bertrand, 

The annotations for the track 1 is given in the test folders (e.g. in test/english/120s/) in the *s.item files (e.g. test/english/120s/120s.item). These give you the timestamps for the phones in the files in the test folders. 
The transcriptions for the train dataset is purposely not given. 

Julien,
The ZeroSpeech Challenge Team

**Comment by bhigy** [comment]
Ok, thanks! From the challenge description, I understood that transcription would be provided for the training data as well.

Best,
Bertrand
